### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by YeetDragon23** [ellieeet123/ellieeet123.github.io#4]
Hello! I noticed that at the top of the repository it said "GitHub Pages Failed" and decided to look into that because i was able to access ellieeet123.github.io. Naturally I first clicked on the red X to the right of it, and it said something about "failed deployment" or something like that.

So i looked at the part of deployment that failed and it looks like this:
`{"message":"Deployment request failed for 4890079b90a6e9d2d857e40d4bed3bda40a9906f due to in progress deployment. Please cancel 7a9ba1678ed47752f66cfc9e3855cf0834350299 first or wait for it to complete.","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-github-pages-deployment"}`
Based on:
`Deployment request failed for 4890079b90a6e9d2d857e40d4bed3bda40a9906f due to in progress deployment. Please cancel 7a9ba1678ed47752f66cfc9e3855cf0834350299 first or wait for it to complete.`
this may be because a commit happened during the deployment and something went wrong. I then opened up https://docs.github.com/rest/reference/repos#create-a-github-pages-deployment (which was in the error thing) and didn't find many interesting things but i'll look at it more. (the long strings of numbers and letters probably mean the repository ID and the commit ID)

Also i saw there were alternate links, specifically pring-site.github.io which is a fork of this repository. Theoretically, its possible to find out if something is wrong with the files and get back to this repository. The main thing for pring-site.github.io repository is that it said "Last stable version" which was February 28 (according to the repository) which was not 19 days ago (i hope) when this repository stopped working.

I hope this helps, if you have any questions i'll try to answer them

**Comment by ellieeet123** [comment]
Hey! Thanks for this issue report, I appreciate you taking the time to look into this. It turns out that the reason the pages build failed was just due to Github Pages having a temporary error/outage (https://www.githubstatus.com/incidents/z95g34pl8rdm) and since then it's been working fine. I just haven't added any new commits since then because I've been really busy with school and other IRL stuff. Also, as for the pring-site fork, this site currently is on a stable version (the only time it's not is when I'm testing some sort of new site feature), and I just haven't updated that in a while due to the same reason.
